neovim:
  exe: nvim
  dir:
    - ~/.config/nvim
  config:
    - init.lua
    - lua
    - ftplugin
    - bg
  dependencies:
    - fd
    - ripgrep
    - fzf
    - lazygit
    - gnu-sed
tmux:
  exe: tmux
  dir:
    - ~/.config/tmux
  config:
    - .tmux.conf
kitty:
  exe: kitty
  dir:
    - ~/.config/kitty
  config:
    - kitty.conf
